Repository DeveloperAcademy-POSTECH/2024-MacC-M13-3I, pull requests merged in 2024-11, with the labels that each got.

#2 [Setting] 파일 세팅
  PennyPack.xcodeproj/project.pbxproj
  PennyPack/Source/App/PennyPackApp.swift
  PennyPack/Source/View/CalendarView.swift
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/ContentView.swift
  PennyPack/Source/View/MainView.swift
  PennyPack/Source/View/ReceiptView.swift
  PennyPack/Source/View/ResultView.swift
  PennyPack/Source/View/ScanView.swift
Labels: 💧SISI

#7 [Feat] 카트뷰
  PennyPack/Source/View/CartView.swift
Labels: ❄️ Winter

#11 [Setting] Color setting
  PennyPack/Assets.xcassets/Color/Contents.json
  PennyPack/Assets.xcassets/Color/RBackgroundGray.colorset/Contents.json
  PennyPack/Assets.xcassets/Color/RBlack.colorset/Contents.json
  PennyPack/Assets.xcassets/Color/RCameraBlack.colorset/Contents.json
  PennyPack/Assets.xcassets/Color/RLightGray.colorset/Contents.json
  PennyPack/Assets.xcassets/Color/RMainBlue.colorset/Contents.json
  PennyPack/Assets.xcassets/Color/RPink.colorset/Contents.json
  PennyPack/Assets.xcassets/Color/RRed.colorset/Contents.json
  PennyPack/Assets.xcassets/Color/RStrokeGray.colorset/Contents.json
Labels: 💧SISI

#16 [Feat]-list 생성
  PennyPack.xcodeproj/project.pbxproj
  PennyPack/Source/App/PennyPackApp.swift
  PennyPack/Source/View/CalendarView.swift
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/ContentView.swift
  PennyPack/Source/View/ReceiptView.swift
  PennyPack/Source/View/ResultView.swift
  PennyPack/Source/View/ScanView.swift
  PennyPack/ViewModel/DocumentScannerView.swift
  PennyPack/ViewModel/ListModel.swift
  PennyPack/ViewModel/TranslationSerivce.swift
Labels: 💧SISI

#17 [Feat]#6 - 정규표현식 연습
  PennyPack/Source/App/PennyPackApp.swift
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/ContentView.swift
  PennyPack/Source/View/MainView.swift
  PennyPack/Source/View/ScanView.swift
Labels: ❄️ Winter

#20 [Feat] 머지 오류난 코드 수정
  PennyPack.xcodeproj/project.pbxproj
  PennyPack/Source/App/PennyPackApp.swift
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/ContentView.swift
  PennyPack/Source/View/MainView.swift
  PennyPack/Source/View/ScanView.swift
  PennyPack/Source/View/TestView.swift
Labels: 💧SISI

#22 [Feat] - 뷰 구조화
  PennyPack.xcodeproj/project.pbxproj
  PennyPack/Assets.xcassets/France.imageset/Contents.json
  PennyPack/Assets.xcassets/France.imageset/france1.png
  PennyPack/Font/FontExtension.swift
  PennyPack/Info.plist
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/ContentView.swift
  PennyPack/Source/View/LanguageSelectedView.swift
  PennyPack/Source/View/MainView.swift
  PennyPack/Source/View/ReceiptView.swift
  PennyPack/Source/View/ResultView.swift
  PennyPack/Source/View/TestView.swift
  PennyPack/ViewModel/ListModel.swift
  PennyPack/ViewModel/OtherFuncs.swift
  PennyPack/ViewModel/ShoppingListModel.swift
  PennyPack/ViewModel/TranslationSerivce.swift
Labels: 💧SISI

#24 [Feat] 정규표현식 함수 테스트
  PennyPack.xcodeproj/project.pbxproj
  PennyPack/Source/View/Regex.swift
  PennyPack/ViewModel/OtherFuncs.swift
Labels: ❄️ Winter

#26 [Feat] - 리스트들 UserDefaults로 저장
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/ContentView.swift
  PennyPack/Source/View/MainView.swift
  PennyPack/Source/View/ResultView.swift
  PennyPack/Source/View/ScanView.swift
  PennyPack/ViewModel/ListModel.swift
  PennyPack/ViewModel/ShoppingListModel.swift
  PennyPack/ViewModel/TranslationSerivce.swift
Labels: 💧SISI

#28 [Feat] #25 정규표현식 가격 뽑아내기
  PennyPack/Source/View/Regex.swift
  PennyPack/Source/View/ScanView.swift
  PennyPack/ViewModel/OtherFuncs.swift
Labels: ❄️ Winter

#30 [Feat] #27 - 기록 저장 후 보여주기
  PennyPack.xcodeproj/project.pbxproj
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/ContentView.swift
  PennyPack/Source/View/DropdownMenu.swift
  PennyPack/Source/View/MainView.swift
  PennyPack/Source/View/ResultView.swift
  PennyPack/Source/View/TestView.swift
  PennyPack/Source/ViewSource/DropdownListView.swift
  PennyPack/Source/ViewSource/LanguageSelectedView.swift
  PennyPack/Source/ViewSource/ListView.swift
  PennyPack/Source/ViewSource/ResultModalView.swift
  PennyPack/Source/ViewSource/TestView.swift
  PennyPack/ViewModel/ListModel.swift
  PennyPack/ViewModel/ShoppingListModel.swift
Labels: 💧SISI

#31 [Feat] #29 정규표현식 수정 미완
  PennyPack/Source/View/Regex.swift
Labels: ❄️ Winter

#32 [Feat] - 기록들 저장& 보여주기 전체 정리 완료.
  PennyPack/Source/View/CalendarView.swift
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/ContentView.swift
  PennyPack/Source/View/MainView.swift
  PennyPack/Source/View/ReceiptView.swift
  PennyPack/Source/View/ResultView.swift
  PennyPack/Source/ViewSource/DropdownListView.swift
  PennyPack/Source/ViewSource/ListView.swift
  PennyPack/Source/ViewSource/ResultModalView.swift
  PennyPack/Source/ViewSource/TestView.swift
  PennyPack/ViewModel/ListModel.swift
  PennyPack/ViewModel/ShoppingListModel.swift
Labels: 💧SISI

#34 [Design] ScanView 수정하려면 customCamera로 가야함.
  PennyPack.xcodeproj/project.pbxproj
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/ScanView.swift
  PennyPack/Source/ViewSource/TestView.swift
  PennyPack/Ubea/TestDocumentScannerView.swift
  PennyPack/Ubea/TestView.swift
  PennyPack/ViewModel/ShoppingListModel.swift
Labels: 💧SISI

#36 [Setting] New Font & Color Setting
  PennyPack.xcodeproj/project.pbxproj
  PennyPack/Assets.xcassets/Color/PBackground.colorset/Contents.json
  PennyPack/Assets.xcassets/Color/PBlack.colorset/Contents.json
  PennyPack/Assets.xcassets/Color/PBlue.colorset/Contents.json
  PennyPack/Assets.xcassets/Color/PCameraBlack.colorset/Contents.json
  PennyPack/Assets.xcassets/Color/PDarkGray.colorset/Contents.json
  PennyPack/Assets.xcassets/Color/PGray.colorset/Contents.json
  PennyPack/Assets.xcassets/Color/PLightGray.colorset/Contents.json
  PennyPack/Assets.xcassets/Color/PWhite.colorset/Contents.json
  PennyPack/Font/FontExtension.swift
  PennyPack/Font/Pretendard-Black.otf
  PennyPack/Font/Pretendard-Bold.otf
  PennyPack/Font/Pretendard-Medium.otf
  PennyPack/Font/Pretendard-SemiBold.otf
  PennyPack/Info.plist
  PennyPack/Source/View/CalendarView.swift
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/ContentView.swift
  PennyPack/Source/View/MainView.swift
  PennyPack/Source/View/ReceiptView.swift
  PennyPack/Source/View/ResultView.swift
  PennyPack/Source/View/ScanView.swift
  PennyPack/Source/ViewSource/DropdownListView.swift
  PennyPack/Source/ViewSource/ListView.swift
  PennyPack/Source/ViewSource/ResultModalView.swift
Labels: 💧SISI

#38 [Feat] 정규표현식 상품명
  PennyPack/Source/View/Regex.swift
  PennyPack/Source/View/ScanView.swift
  PennyPack/Ubea/TestView.swift
Labels: ❄️ Winter

#39 [Feat] - 리스트 삭제기능 추가
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/ViewSource/ListView.swift
  PennyPack/ViewModel/ListModel.swift
  PennyPack/ViewModel/ShoppingListModel.swift
Labels: 💧SISI

#42 [Design] UI공사중
  PennyPack/Assets.xcassets/Background.imageset/Contents.json
  PennyPack/Assets.xcassets/Background.imageset/Pennypack_BackgroundImage.png
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/ContentView.swift
  PennyPack/Source/View/MainView.swift
  PennyPack/Source/ViewSource/DropdownListView.swift
  PennyPack/Source/ViewSource/ListView.swift
  PennyPack/Ubea/TestView.swift
  PennyPack/ViewModel/ListModel.swift
Labels: 💧SISI

#44 [Design] ui 1차 공사 완.
  PennyPack/Font/FontExtension.swift
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/ContentView.swift
  PennyPack/Source/View/MainView.swift
  PennyPack/Source/View/ResultView.swift
  PennyPack/Source/ViewSource/DropdownListView.swift
  PennyPack/Source/ViewSource/ResultModalView.swift
  PennyPack/ViewModel/ShoppingListModel.swift
Labels: 💧SISI

#49 [Feat] 최종가격 맞게 수정.
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/ContentView.swift
  PennyPack/ViewModel/ShoppingListModel.swift
Labels: 💧SISI

#50 [Feat]#41 카메라 새로 구현
  PennyPack.xcodeproj/project.pbxproj
  PennyPack/Source/View/ScanView.swift
  PennyPack/ViewModel/CameraModel.swift
  PennyPack/ViewModel/CameraPreview.swift
  PennyPack/ViewModel/Scan2Service.swift
Labels: ❄️ Winter

#51 [Feat] 공사 완료
  PennyPack/Assets.xcassets/CalendarBackground.imageset/Contents.json
  PennyPack/Assets.xcassets/CalendarBackground.imageset/Pennypack_CalendarView_Background.png
  PennyPack/Source/View/CalendarView.swift
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/MainView.swift
  PennyPack/Source/View/ReceiptView.swift
  PennyPack/ViewModel/ShoppingListModel.swift
Labels: 💧SISI

#52 [Feat] 앱 중간점검
  PennyPack/Source/View/CartView.swift
  PennyPack/ViewModel/CurrencyService.swift
  PennyPack/ViewModel/ListModel.swift
  PennyPack/ViewModel/ShoppingListModel.swift
Labels: 💧SISI

#56 [Fix] #55 - 머지 후 이슈난거 수정함.
  PennyPack/Source/View/CartView.swift
Labels: 💧SISI

#59 [Feat] 텍스트버튼 누르면 항목 추가
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/ViewSource/ListView.swift
  PennyPack/Source/ViewSource/ResultModalView.swift
  PennyPack/ViewModel/ShoppingListModel.swift
Labels: 💧SISI

#58 [Feat] #41 카메라+OCR 기능 추가
  PennyPack.xcodeproj/project.pbxproj
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/ContentView.swift
  PennyPack/Source/View/Regex.swift
  PennyPack/Source/View/ScanView.swift
  PennyPack/Ubea/TestView.swift
  PennyPack/ViewModel/CameraService.swift
  PennyPack/ViewModel/CameraViewModel.swift
  PennyPack/ViewModel/DocumentScannerView.swift
  PennyPack/ViewModel/TranslationSerivce.swift
Labels: ❄️ Winter

#62 Hotfix/#61 카메라+OCR 대수술 완료
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/ScanView.swift
  PennyPack/ViewModel/CameraModel.swift
  PennyPack/ViewModel/CameraViewModel.swift
  PennyPack/ViewModel/DocumentScannerView.swift
  PennyPack/ViewModel/TranslationSerivce.swift
Labels: ❄️ Winter

#64 Feat/#63 전체적인 코드 수정
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/ContentView.swift
  PennyPack/Source/View/Regex.swift
  PennyPack/Source/View/ScanView.swift
  PennyPack/Ubea/TestView.swift
  PennyPack/ViewModel/DocumentScannerView.swift
  PennyPack/ViewModel/ShoppingListModel.swift
  PennyPack/ViewModel/TranslationSerivce.swift
Labels: ❄️ Winter

#66 [Feat] 스캔뷰 카메라 데이터 연결, 유로 더블 수정
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/Regex.swift
  PennyPack/Source/ViewSource/ResultModalView.swift
  PennyPack/ViewModel/ShoppingListModel.swift
Labels: ❄️ Winter

#68 [Feat] - add리스트했을때 가격 변화 완벽수정
  PennyPack.xcodeproj/project.pbxproj
  PennyPack/Source/View/CalendarView.swift
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/ReceiptView.swift
  PennyPack/ViewModel/ShoppingListModel.swift
Labels: 💧SISI

#70 [Fix] - 출시로 가기위한 수정에수정에 수정
  PennyPack/Source/View/CalendarView.swift
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/ReceiptView.swift
  PennyPack/ViewModel/OtherFuncs.swift
  PennyPack/ViewModel/ShoppingListModel.swift
Labels: 💧SISI

#71 [Feat] 카트뷰 리스트 이름, 가격 형식 수정
  PennyPack/Source/View/CartView.swift
Labels: ❄️ Winter

#72 [Fix] - 이친구가 중괄호 구라쳐서 윈터랑 씨씨랑 눈빠질뻔;;
  PennyPack/Source/View/CartView.swift
Labels: 💧SISI

#74 [Feat] 카메라뷰 ui
  PennyPack.xcodeproj/project.pbxproj
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/Regex.swift
  PennyPack/Source/View/ScanView.swift
  PennyPack/ViewModel/DocumentScannerView.swift
  PennyPack/ViewModel/TranslationSerivce.swift
Labels: ❄️ Winter

#77 [Fix] - 짜잘 & 잔잔바리쓰들 수정쓰
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/MainView.swift
  PennyPack/Source/View/ReceiptView.swift
  PennyPack/Source/ViewSource/ResultModalView.swift
  PennyPack/ViewModel/ShoppingListModel.swift
Labels: 💧SISI

#78 Feat/#73 카메라뷰 수정 완
  PennyPack.xcodeproj/project.pbxproj
  PennyPack/Assets.xcassets/Color/PBackground.colorset/Contents.json
  PennyPack/Assets.xcassets/Color/PBlack.colorset/Contents.json
  PennyPack/Assets.xcassets/Color/PBlue.colorset/Contents.json
  PennyPack/Assets.xcassets/Color/PCameraBlack.colorset/Contents.json
  PennyPack/Assets.xcassets/Color/PDarkGray.colorset/Contents.json
  PennyPack/Assets.xcassets/Color/PGray.colorset/Contents.json
  PennyPack/Assets.xcassets/Color/PLightGray.colorset/Contents.json
  PennyPack/Assets.xcassets/Color/PWhite.colorset/Contents.json
  PennyPack/Source/View/MainView.swift
  PennyPack/Source/View/Regex.swift
  PennyPack/Source/View/ScanView.swift
  PennyPack/ViewModel/CameraService.swift
  PennyPack/ViewModel/DocumentScannerView.swift
Labels: ❄️ Winter

#80 [Feat]#79 스캔뷰 대공사
  PennyPack.xcodeproj/project.pbxproj
  PennyPack/Source/View/ScanView.swift
  PennyPack/Ubea/TestView.swift
  PennyPack/ViewModel/DocumentScannerView.swift
  PennyPack/ViewModel/ScannerRetakeView.swift
Labels: ❄️ Winter

#84 [Feat] 스캔뷰 코드 수정
  PennyPack/Source/View/Regex.swift
  PennyPack/Source/View/ScanView.swift
  PennyPack/Ubea/TestView.swift
  PennyPack/ViewModel/ScannerRetakeView.swift
Labels: ❄️ Winter

#86 [Fix] 출시를 위한 준비
  PennyPack.xcodeproj/project.pbxproj
  PennyPack/Source/App/PennyPackApp.swift
  PennyPack/Source/View/CalendarView.swift
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/ContentView.swift
  PennyPack/Source/View/MainView.swift
  PennyPack/Source/View/Regex.swift
  PennyPack/Source/View/ResultView.swift
  PennyPack/Source/View/ScanView.swift
  PennyPack/Source/ViewSource/LanguageSelectedView.swift
  PennyPack/Ubea/CurrencyService.swift
  PennyPack/Ubea/LanguageSelectedView.swift
  PennyPack/Ubea/TestDocumentScannerView.swift
  PennyPack/ViewModel/CameraModel.swift
  PennyPack/ViewModel/CameraPreview.swift
  PennyPack/ViewModel/CameraViewModel.swift
  PennyPack/ViewModel/CurrencyService.swift
  PennyPack/ViewModel/ListModel.swift
  PennyPack/ViewModel/ScannerRetakeView.swift
  PennyPack/ViewModel/ShoppingListModel.swift
  PennyPack/ViewModel/TranslationSerivce.swift
Labels: 💧SISI

#91 [Fix] - 되돌아가즈아
  PennyPack/Source/View/Regex.swift
  PennyPack/Source/View/ScanView.swift
Labels: 💧SISI

#93 [Chore]#85 - 머지 오류난거 원상복귀 확인 후 ScanView 수정
  PennyPack.xcodeproj/project.pbxproj
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/MainView.swift
  PennyPack/Source/View/Regex.swift
  PennyPack/Source/View/ScanView.swift
  PennyPack/ViewModel/ShoppingListModel.swift
Labels: 💧SISI

#95 [Fix] - 잔잔바리쓰들 수정
  PennyPack.xcodeproj/project.pbxproj
  PennyPack.xcodeproj/xcshareddata/xcschemes/PennyPack.xcscheme
  PennyPack/Source/View/CalendarView.swift
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/ContentView.swift
  PennyPack/Source/View/ResultView.swift
  PennyPack/Source/View/ScanView.swift
  PennyPack/Source/ViewSource/LanguageSelectedView.swift
  PennyPack/Source/ViewSource/Regex.swift
  PennyPack/Ubea/CurrencyService.swift
  PennyPack/Ubea/LanguageSelectedView.swift
  PennyPack/Ubea/TestDocumentScannerView.swift
  PennyPack/ViewModel/CameraModel.swift
  PennyPack/ViewModel/CameraPreview.swift
  PennyPack/ViewModel/CameraViewModel.swift
  PennyPack/ViewModel/CurrencyService.swift
  PennyPack/ViewModel/ListModel.swift
  PennyPack/ViewModel/ScannerRetakeView.swift
  PennyPack/ViewModel/ShoppingListModel.swift
  PennyPack/ViewModel/TranslationSerivce.swift
  PennyPackTests/PennyPackTests.swift
Labels: 💧SISI

#98 [Fix] - CustomAlertView 생성 & 커스텀 완료.
  PennyPack.xcodeproj/project.pbxproj
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/ViewSource/CustomAlertView.swift
  PennyPack/Source/ViewSource/Regex.swift
Labels: 💧SISI

#99 [Feat]#97 ResultView -> MainView
  PennyPack.xcodeproj/project.pbxproj
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/MainView.swift
  PennyPack/Source/View/ResultView.swift
Labels: ❄️ Winter

#101 [Fix]#100 머지 오류난 코드 수정
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/ScanView.swift
  PennyPack/Source/ViewSource/CustomAlertView.swift
  PennyPack/Source/ViewSource/Regex.swift
Labels: ❄️ Winter

#103 [Fix] #96 - 이것저것 수정쓰
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/ViewSource/ListView.swift
  PennyPack/Source/ViewSource/Regex.swift
  PennyPack/ViewModel/ListModel.swift
Labels: 💧SISI

#104 [Chore] 주석 제거완료. apiKey 숨기고 출시 가즈아
  PennyPack.xcodeproj/project.pbxproj
  PennyPack/Source/App/PennyPackApp.swift
  PennyPack/Source/View/CartView.swift
  PennyPack/Source/View/MainView.swift
  PennyPack/Source/View/ResultView.swift
  PennyPack/Source/ViewSource/CustomAlertView.swift
Labels: 💧SISI

#105 [Chore] AppIcon
  PennyPack.xcodeproj/project.pbxproj
  PennyPack/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  PennyPack/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: 💧SISI

#107 [HotFix] - APIkey 수정 & BundleID 수정
  PennyPack.xcodeproj/project.pbxproj
  PennyPack.xcodeproj/xcshareddata/xcschemes/PennyPack.xcscheme
  PennyPack/ViewModel/TranslationSerivce.swift
Labels: 💧SISI

#110 [Fix] iPad 삭제
  PennyPack.xcodeproj/project.pbxproj
Labels: 💧SISI

#111 [Fix]#108 - 카메라권한 문구 수정
  PennyPack.xcodeproj/project.pbxproj
Labels: 💧SISI, ❄️ Winter

#114 Fix/#112 - 런치스크린, 알러트 수정
  PennyPack.xcodeproj/project.pbxproj
  PennyPack.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  PennyPack/Assets.xcassets/LaunchScreen.imageset/Contents.json
  PennyPack/Assets.xcassets/LaunchScreen.imageset/LaunchScreen.png
  PennyPack/Info.plist
  PennyPack/Source/View/Launch Screen.storyboard
  PennyPack/Source/ViewSource/CustomAlertView.swift
  PennyPack/ViewModel/TranslationSerivce.swift
Labels: 💧SISI

#115 [Fix] - 원 반영 수정
  PennyPack/Source/View/CartView.swift
  PennyPack/ViewModel/TranslationSerivce.swift
Labels: 💧SISI
